# .github/workflows/norminette.yml
name: norminette
on: [push]
jobs:
  norminette:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: TomWeimer/norminette-action@v3
      with:
        flags: '.'
